Add CloudFormation stack, fix typo
aws-samples/cloudwatch-logs-insights-queries pull request #1
Opened 2021-08-26 05:06 UTC by igorlg

- Added CloudFormation stack to save queries in CloudWatch Logs Insights
- Added CF template/stack description + 1-click deploy button to README
- Fixed typo in README

2021-08-26 16:31 UTC, brianz requested changes
Thank you for the PR! Looks good overall...with the removal of `LogGroupNames` as a restriction, it'll be easier to use and deploy.

2021-08-26 16:31 UTC, brianz commented on README.md
> +Queries described below can be persisted in you CloudWatch Logs Insights page using the CloudFormation template in cloudformation.yaml, or by clicking [![Launch CloudFormation template](https://s3.am
small typo: `s/you CloudWatch/your CloudWatch/`

2021-08-26 16:31 UTC, brianz commented on README.md
> +Queries described below can be persisted in you CloudWatch Logs Insights page using the CloudFormation template in cloudformation.yaml, or by clicking [![Launch CloudFormation template](https://s3.am
Great idea on the quick launch button!

2021-08-26 16:31 UTC, brianz commented on cloudformation.yaml
> +    Description: "(Required) List of CloudWatch Log Groups to apply queries to."
Let's remove the limitation of applying queries to specific log groups. It's easier to create these queries so that they can be applied to any log group.

I removed this parameter and `LogGroupNames` from the `QueryDefinition`s and it makes this stack much easier to deploy. The queries are also easier to run since you can select any log group in the console.

2021-09-08 09:16 UTC, igorlg commented on README.md
> +Queries described below can be persisted in you CloudWatch Logs Insights page using the CloudFormation template in cloudformation.yaml, or by clicking [![Launch CloudFormation template](https://s3.am
Typo fixed! Thank you!

2021-09-08 09:17 UTC, igorlg commented on README.md
> +Queries described below can be persisted in you CloudWatch Logs Insights page using the CloudFormation template in cloudformation.yaml, or by clicking [![Launch CloudFormation template](https://s3.am
Thank you!

2021-09-08 09:25 UTC, igorlg commented on cloudformation.yaml
> +    Description: "(Required) List of CloudWatch Log Groups to apply queries to."
Done. Removed the parameter and references from QueryDefinition. Thanks for pointing that out.

2021-09-08 21:58 UTC, merged